{{- if .Values.global.configValidation }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: istio-validator-{{ .Values.revision | default "default" }}-{{ .Release.Namespace }}
  labels:
    maistra-version: "2.5.10"
    app: istiod
    release: {{ .Release.Name }}
    istio: istiod
    istio.io/rev: {{ .Values.revision | default "default" | quote }}
webhooks:
  # Webhook handling per-revision validation. Mostly here so we can determine whether webhooks
  # are rejecting invalid configs on a per-revision basis.
  - name: rev.validation.istio.io
    clientConfig:
      # Should change from base but cannot for API compat
      {{- if .Values.base.validationURL }}
      url: {{ .Values.base.validationURL }}
      {{- else }}
      service:
        name: istiod-{{ .Values.revision | default "default" }}
        namespace: {{ .Release.Namespace }}
        path: "/validate"
      {{- end }}
    namespaceSelector:
      matchExpressions:
      - key: maistra.io/member-of
        operator: In
        values:
        - {{ .Release.Namespace }}
    objectSelector:
      matchExpressions:
      - key: maistra-version
        operator: DoesNotExist
    rules:
      - operations:
        - CREATE
        - UPDATE
        apiGroups:
        - authentication.maistra.io
        apiVersions:
        - "*"
        resources:
        - "*"
      - operations:
        - CREATE
        - UPDATE
        apiGroups:
        - rbac.maistra.io
        apiVersions:
        - "*"
        resources:
        - "*"

      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - security.istio.io
        apiVersions:
          - v1beta1
          - v1
        resources:
          - authorizationpolicies
          - requestauthentications

      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - security.istio.io
        apiVersions:
          - v1beta1
        resources:
          - peerauthentications

      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - networking.istio.io
        apiVersions:
          - v1alpha3
          - v1beta1
        resources:
          - destinationrules
          - gateways
          - serviceentries
          - sidecars
          - virtualservices
          - workloadentries
          - workloadgroups

      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - networking.istio.io
        apiVersions:
          - v1alpha3
        resources:
          - envoyfilters

      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - networking.istio.io
        apiVersions:
          - v1beta1
        resources:
          - proxyconfigs

      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - telemetry.istio.io
        apiVersions:
          - v1alpha1
        resources:
          - telemetries

      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - extensions.istio.io
        apiVersions:
          - v1alpha1
        resources:
          - wasmplugins

    # Fail open until the validation webhook is ready. The webhook controller
    # will update this to `Fail` and patch in the `caBundle` when the webhook
    # endpoint is ready.
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1beta1", "v1"]
---
{{- end }}
